### ISSUE TITLE
A304 conflicts with flexible mesh conventions

### ISSUE THREAD

**Issue by trexfeathers** [pp-mo/ugrid-checks#34]
UGRID conformance rule [A304](https://ugrid-conventions.readthedocs.io/en/conformance/conformance/#A304) states that no connectivity ending in `_node_connectivity` should have a `_FillValue`.

UGRID's [2D flexible mesh topology](https://ugrid-conventions.readthedocs.io/en/conformance/#2d-flexible-mesh-mixed-triangles-quadrilaterals-etc-topology) depends on using `_FillValue` for elements that connect to fewer than the maximum number of nodes.

**Comment by pp-mo** [comment]
#36 fixes this

N.B. also, the [relevant new commit to the UGRID repo](https://github.com/ugrid-conventions/ugrid-conventions/pull/54/commits/390ec659cf22d25382457bc9e8794154e70413c8) updates the conformance page (still in unmerged PR),
so those changes appear in the preliminary RTD pages [latest build](https://readthedocs.org/projects/ugrid-conventions/builds/16205143/)
